name: Trigger Fork Repo ActionðŸŒˆ

on:
  push:
    branches:
      - main

jobs:
  trigger-fork:
    if: github.repository_owner == 'subject-test-01'
    runs-on: ubuntu-latest
    steps:
      - run: echo "main branch pushed"
